# This is a basic workflow that is manually triggered

name: auto_Reserve

on:
  schedule:
    # GitHub Actions 使用 UTC 时间
    # 北京时间 07:58 = UTC 23:58
    # 提前启动，让程序等待到学校8:00开放
    - cron: "58 23 * * *"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: install dependency
        run: |
          python -m pip install --upgrade pip
          sudo apt-get install build-essential libssl-dev libffi-dev python3-dev -y
          pip install cryptography requests opencv-python

      - name: run script
        env:
          USERNAMES: ${{ secrets.USERNAMES }}
          PASSWORDS: ${{ secrets.PASSWORDS }}
        run: |
          python main.py --action
